<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<body>

	<a href="http://<?php echo $this->url ?>/forgotpassword/change?ecid=<?php echo $this->emailConfirmationId ?>">http://<?php echo $this->url ?>/forgotpassword/change?ecid=<?php echo $this->emailConfirmationId ?></a>

</body>
</html>